// ========== ENUMS ==========

export enum UserRole {
  CEO = "CEO",
  RESPONSABILE_REPARTO = "RESPONSABILE_REPARTO",
  RISORSA_UMANA = "RISORSA_UMANA",
  CONSULENTE = "CONSULENTE",
  DIPENDENTE = "DIPENDENTE",
  DEVELOPER = "DEVELOPER",
  AMMINISTRAZIONE = "AMMINISTRAZIONE",
}

export enum Seniority {
  JUNIOR = "JUNIOR",
  MID = "MID",
  SENIOR = "SENIOR",
}

export enum SelectionStatus {
  FATTURA_AV_SALDATA = "FATTURA_AV_SALDATA",
  HR_ASSEGNATA = "HR_ASSEGNATA",
  PRIMA_CALL_COMPLETATA = "PRIMA_CALL_COMPLETATA",
  RACCOLTA_JOB_IN_APPROVAZIONE_CLIENTE = "RACCOLTA_JOB_IN_APPROVAZIONE_CLIENTE",
  RACCOLTA_JOB_APPROVATA_CLIENTE = "RACCOLTA_JOB_APPROVATA_CLIENTE",
  BOZZA_ANNUNCIO_IN_APPROVAZIONE_CEO = "BOZZA_ANNUNCIO_IN_APPROVAZIONE_CEO",
  ANNUNCIO_APPROVATO = "ANNUNCIO_APPROVATO",
  ANNUNCIO_PUBBLICATO = "ANNUNCIO_PUBBLICATO",
  CANDIDATURE_RICEVUTE = "CANDIDATURE_RICEVUTE",
  COLLOQUI_IN_CORSO = "COLLOQUI_IN_CORSO",
  PROPOSTA_CANDIDATI = "PROPOSTA_CANDIDATI",
  CHIUSA = "CHIUSA",
  ANNULLATA = "ANNULLATA",
}

export enum PackageType {
  BASE = "BASE",
  MDO = "MDO",
}

export enum InvoiceType {
  AV = "AV",
  INS = "INS",
  MDO = "MDO",
}

export enum AnnouncementPlatform {
  LINKEDIN = "LINKEDIN",
  INDEED = "INDEED",
  ALTRO = "ALTRO",
}

export enum AnnouncementStatus {
  BOZZA = "BOZZA",
  PUBBLICATO = "PUBBLICATO",
  SCADUTO = "SCADUTO",
  CHIUSO = "CHIUSO",
}

export enum ApplicationStatus {
  RICEVUTA = "RICEVUTA",
  TEST_INVIATO = "TEST_INVIATO",
  TEST_COMPLETATO = "TEST_COMPLETATO",
  PRIMO_COLLOQUIO_PROGRAMMATO = "PRIMO_COLLOQUIO_PROGRAMMATO",
  PRIMO_COLLOQUIO_EFFETTUATO = "PRIMO_COLLOQUIO_EFFETTUATO",
  COLLOQUIO_CEO_PROGRAMMATO = "COLLOQUIO_CEO_PROGRAMMATO",
  COLLOQUIO_CEO_EFFETTUATO = "COLLOQUIO_CEO_EFFETTUATO",
  ASSUNTO = "ASSUNTO",
  SCARTATO = "SCARTATO",
}

export enum InterviewOutcome {
  POSITIVO = "POSITIVO",
  NEGATIVO = "NEGATIVO",
  NEUTRO = "NEUTRO",
}

export enum ContractType {
  FULL_TIME = "FULL_TIME",
  PART_TIME = "PART_TIME",
  COLLABORAZIONE = "COLLABORAZIONE",
  STAGE = "STAGE",
}

export enum WorkMode {
  IN_PRESENZA = "IN_PRESENZA",
  IBRIDO = "IBRIDO",
  DA_REMOTO = "DA_REMOTO",
}

export enum LanguageType {
  ITALIANO = "ITALIANO",
  INGLESE = "INGLESE",
  ALTRO = "ALTRO",
}
