// types/enums.ts

export enum UserRole {
  CEO = "CEO",
  RESPONSABILE_REPARTO = "RESPONSABILE_REPARTO",
  RISORSA_UMANA = "RISORSA_UMANA",
  DIPENDENTE = "DIPENDENTE",
  DEVELOPER = "DEVELOPER",
}

export enum Seniority {
  JUNIOR = "JUNIOR",
  MID = "MID",
  SENIOR = "SENIOR",
}

export enum SelectionStatus {
  CREATA = "CREATA",
  APPROVATA = "APPROVATA",
  IN_CORSO = "IN_CORSO",
  ANNUNCI_PUBBLICATI = "ANNUNCI_PUBBLICATI",
  CANDIDATURE_RICEVUTE = "CANDIDATURE_RICEVUTE",
  COLLOQUI_IN_CORSO = "COLLOQUI_IN_CORSO",
  COLLOQUI_CEO = "COLLOQUI_CEO",
  CHIUSA = "CHIUSA",
  ANNULLATA = "ANNULLATA",
}

export enum SelectionType {
  INTERNO = "INTERNO",
  ESTERNO = "ESTERNO",
}

export enum AnnouncementPlatform {
  LINKEDIN = "LINKEDIN",
  INDEED = "INDEED",
  ALTRO = "ALTRO",
}

export enum AnnouncementStatus {
  BOZZA = "BOZZA",
  PUBBLICATO = "PUBBLICATO",
  SCADUTO = "SCADUTO",
  CHIUSO = "CHIUSO",
}

export enum ApplicationStatus {
  RICEVUTA = "RICEVUTA",
  TEST_INVIATO = "TEST_INVIATO",
  TEST_COMPLETATO = "TEST_COMPLETATO",
  PRIMO_COLLOQUIO_PROGRAMMATO = "PRIMO_COLLOQUIO_PROGRAMMATO",
  PRIMO_COLLOQUIO_EFFETTUATO = "PRIMO_COLLOQUIO_EFFETTUATO",
  COLLOQUIO_CEO_PROGRAMMATO = "COLLOQUIO_CEO_PROGRAMMATO",
  COLLOQUIO_CEO_EFFETTUATO = "COLLOQUIO_CEO_EFFETTUATO",
  ASSUNTO = "ASSUNTO",
  SCARTATO = "SCARTATO",
}

export enum InterviewOutcome {
  POSITIVO = "POSITIVO",
  NEGATIVO = "NEGATIVO",
  NEUTRO = "NEUTRO",
}
